[[constraint]]
  name = "github.com/confluentinc/confluent-kafka-go"
  revision = "9fa7efcf0471e6d18d6ba2756abaa18de84a0415"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.18.1"

[[constraint]]
  name = "github.com/secmask/go-redisproto"
  revision = "14323b204640af1628764b06726c64fe040998e1"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.5.3"
